import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import SkillCard from "../components/SkillCard";
import Navbar from "../components/Navbar";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common", "index"])),
    },
  };
}

const Home: NextPage = () => {
  const { t: tc } = useTranslation("common");

  return (
    <div>
      <Head>
        <title>{tc`metaTitle`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="pt-24">
        <h1 className="text-2xl text-primary text-center">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="text-center">
          <code className="text-success">pages/index.tsx</code>
        </p>

        <div className="flex items-center flex-col">
          <div className="grid grid-cols-3 gap-7">
            {"123456789".split("").map((n) => (
              <SkillCard key={"s-" + n} />
            ))}
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
